branch-defaults:
  ENTER:
    environment: null
  default:
    environment: null
  master:
    environment: null
environment-defaults:
  stocks:
    branch: null
    repository: null
global:
  application_name: stocks
  branch: ENTER
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.4 running
    on 64bit Amazon Linux/2.4.2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: stocksRepo
  sc: git
  workspace_type: Application
