# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Stock',
        ),
    ]
